# Generated by Django 5.2.5 on 2025-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Waiter', 'Waiter'), ('Cashier', 'Cashier')], default='Staff', max_length=50),
        ),
    ]
